name: fmt, clippy, rustdocs

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rustdoc:
    runs-on: ubuntu-latest
    steps:
      - name: Run rustdoc
        run: rustdoc src/lib.rs --crate-name max-docs
      - name: archive
        run: zip -r max-docs ./docs/max-docs
      - name : upload artifacts
        uses: actions/upload-artifact@v3
        with: 
            name: rustdoc
            path: max-docs.zip
            retention-days: 2


    
