name: fmt, clippy, rustdocs

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rustdoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v3
        with: 
            name: rustdoc
            path: max-docs.zip
            retention-days: 2
      - name: Output rustdoc
        run: | 
          cargo doc
          zip -r max-docs ./docs/target/doc

    
