name: rustdocs

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  rustdoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run rustdoc
        run: |
          rustup target add thumbv7em-none-eabihf
          cargo doc --no-deps --document-private-items
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with: 
            name: rustdoc
            path: target/doc
            retention-days: 2
